namespace Isis.Server.Models
{
    using System;

    /// <summary>
    /// A create/update request body for a credential. The access key and secret key are generated by the
    /// server on create and never accepted from the client; the raw secret is returned only once, at creation.
    /// </summary>
    public class CredentialUpsertRequest
    {
        #region Public-Members

        /// <summary>
        /// Human-readable credential name.
        /// </summary>
        public string? Name { get; set; } = null;

        /// <summary>
        /// The owning user identifier. Required on create.
        /// </summary>
        public string? UserId { get; set; } = null;

        /// <summary>
        /// Whether the credential is active.
        /// </summary>
        public bool Active { get; set; } = true;

        /// <summary>
        /// Optional UTC expiration timestamp.
        /// </summary>
        public DateTime? ExpirationUtc { get; set; } = null;

        #endregion

        #region Constructors-and-Factories

        /// <summary>
        /// Instantiate a credential upsert request.
        /// </summary>
        public CredentialUpsertRequest()
        {
        }

        #endregion
    }
}
